Lab06: Main.o Test.o
	g++ -g -std=c++11 -Wall  Main.o Test.o -o Lab06
	
Main.o: Main.cpp Sorts.h Sorts.hpp Test.h
	g++ -g -std=c++11 -Wall -c Main.cpp

Test.o: Test.h Test.cpp
	g++ -g -std=c++11 -Wall -c Test.cpp	

clean: 
	rm *.o Lab06












